import Head from "next/head";
import { FormEvent, useEffect, useReducer, useState } from 'react'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Button from "@/components/Button";
import Image from "next/image";
import { BiCircle } from 'react-icons/bi'
import Link from "next/link";
import { ICms, INews, IReducerAction } from '@/interfaces'
import { IProduct } from "@/interfaces";
import Product from "@/components/ProductCard";
import dbConnect from '@/lib/dbConnection';
import CmsModel from '@/models/CmsModel';
import ProductModel from '@/models/ProductModel';
import { useRouter } from "next/router";
import MyImage from "@/assets/news.png"


export default function Home({ cms, products }: { cms: ICms, products: IProduct[] }) {
  const router = useRouter()

  const handleClick = (id: any) => {
    router.push(`/products/${id}`)
  }

  return (
    <div>
      <Head>
        <title>Eraskon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconimg.png" />
      </Head>
      <div className="">
        {/* {loading && <Loader modalOpen={true} />} */}
        <Header />
        <section className="section relative top-section h-[80vh]  pb-12 overflow-hidden flex justify-center items-center lg:min-h-screen bg-blue lg:mt-0 lg:pt-40">
          <svg className="absolute inset-0 h-screen" viewBox='0 0 1600 800'><rect fill='#090F3B' width='1600' height='800' /><g fillOpacity='1'><path fill='#0a1040' d='M486 705.8c-109.3-21.8-223.4-32.2-335.3-19.4C99.5 692.1 49 703 0 719.8V800h843.8c-115.9-33.2-230.8-68.1-347.6-92.2C492.8 707.1 489.4 706.5 486 705.8z' /><path fill='#0b1145' d='M1600 0H0v719.8c49-16.8 99.5-27.8 150.7-33.5c111.9-12.7 226-2.4 335.3 19.4c3.4 0.7 6.8 1.4 10.2 2c116.8 24 231.7 59 347.6 92.2H1600V0z' /><path fill='#0b134b' d='M478.4 581c3.2 0.8 6.4 1.7 9.5 2.5c196.2 52.5 388.7 133.5 593.5 176.6c174.2 36.6 349.5 29.2 518.6-10.2V0H0v574.9c52.3-17.6 106.5-27.7 161.1-30.9C268.4 537.4 375.7 554.2 478.4 581z' /><path fill='#0c1450' d='M0 0v429.4c55.6-18.4 113.5-27.3 171.4-27.7c102.8-0.8 203.2 22.7 299.3 54.5c3 1 5.9 2 8.9 3c183.6 62 365.7 146.1 562.4 192.1c186.7 43.7 376.3 34.4 557.9-12.6V0H0z' /><path fill='#0D1555' d='M181.8 259.4c98.2 6 191.9 35.2 281.3 72.1c2.8 1.1 5.5 2.3 8.3 3.4c171 71.6 342.7 158.5 531.3 207.7c198.8 51.8 403.4 40.8 597.3-14.8V0H0v283.2C59 263.6 120.6 255.7 181.8 259.4z' /><path fill='#0e165b' d='M1600 0H0v136.3c62.3-20.9 127.7-27.5 192.2-19.2c93.6 12.1 180.5 47.7 263.3 89.6c2.6 1.3 5.1 2.6 7.7 3.9c158.4 81.1 319.7 170.9 500.3 223.2c210.5 61 430.8 49 636.6-16.6V0z' /><path fill='#0f1860' d='M454.9 86.3C600.7 177 751.6 269.3 924.1 325c208.6 67.4 431.3 60.8 637.9-5.3c12.8-4.1 25.4-8.4 38.1-12.9V0H288.1c56 21.3 108.7 50.6 159.7 82C450.2 83.4 452.5 84.9 454.9 86.3z' /><path fill='#0f1966' d='M1600 0H498c118.1 85.8 243.5 164.5 386.8 216.2c191.8 69.2 400 74.7 595 21.1c40.8-11.2 81.1-25.2 120.3-41.7V0z' /><path fill='#101b6b' d='M1397.5 154.8c47.2-10.6 93.6-25.3 138.6-43.8c21.7-8.9 43-18.8 63.9-29.5V0H643.4c62.9 41.7 129.7 78.2 202.1 107.4C1020.4 178.1 1214.2 196.1 1397.5 154.8z' /><path fill='#111C71' d='M1315.3 72.4c75.3-12.6 148.9-37.1 216.8-72.4h-723C966.8 71 1144.7 101 1315.3 72.4z' /></g></svg>
          <svg className="absolute inset-0 h-screen opacity-20" xmlns="http://www.w3.org/2000/svg" version="1.1" width="1440" height="560" preserveAspectRatio="none" viewBox="0 0 1440 560">
            <g mask="url(&quot;#SvgjsMask1218&quot;)" fill="none">
              <use href="#SvgjsSymbol1225" x="0" y="0"></use>
              <use href="#SvgjsSymbol1225" x="720" y="0"></use>
            </g>
            <defs>
              <mask id="SvgjsMask1218">
                <rect width="1440" height="560" fill="#ffffff"></rect>
              </mask>
              <path d="M-1 0 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0z" id="SvgjsPath1222"></path>
              <path d="M-3 0 a3 3 0 1 0 6 0 a3 3 0 1 0 -6 0z" id="SvgjsPath1220"></path>
              <path d="M-5 0 a5 5 0 1 0 10 0 a5 5 0 1 0 -10 0z" id="SvgjsPath1221"></path>
              <path d="M2 -2 L-2 2z" id="SvgjsPath1223"></path>
              <path d="M6 -6 L-6 6z" id="SvgjsPath1219"></path>
              <path d="M30 -30 L-30 30z" id="SvgjsPath1224"></path>
            </defs>
            <symbol id="SvgjsSymbol1225">
              <use href="#SvgjsPath1219" x="30" y="30" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1220" x="30" y="90" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="30" y="150" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="30" y="210" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="30" y="270" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="30" y="330" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="30" y="390" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1220" x="30" y="450" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="30" y="510" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1222" x="30" y="570" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="90" y="30" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="90" y="90" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="90" y="150" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="90" y="210" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="90" y="270" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="90" y="330" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1224" x="90" y="390" stroke="rgba(255, 222, 90, 1)" strokeWidth="3"></use>
              <use href="#SvgjsPath1220" x="90" y="450" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="90" y="510" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="90" y="570" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1220" x="150" y="30" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="150" y="90" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="150" y="150" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="150" y="210" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="150" y="270" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="150" y="330" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="150" y="390" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="150" y="450" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1224" x="150" y="510" stroke="rgba(255, 222, 90, 1)" strokeWidth="3"></use>
              <use href="#SvgjsPath1223" x="150" y="570" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="210" y="30" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="210" y="90" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1222" x="210" y="150" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="210" y="210" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="210" y="270" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="210" y="330" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="210" y="390" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="210" y="450" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="210" y="510" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1222" x="210" y="570" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1224" x="270" y="30" stroke="rgba(255, 222, 90, 1)" strokeWidth="3"></use>
              <use href="#SvgjsPath1219" x="270" y="90" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1224" x="270" y="150" stroke="rgba(255, 222, 90, 1)" strokeWidth="3"></use>
              <use href="#SvgjsPath1222" x="270" y="210" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1222" x="270" y="270" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="270" y="330" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1220" x="270" y="390" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="270" y="450" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1224" x="270" y="510" stroke="rgba(255, 222, 90, 1)" strokeWidth="3"></use>
              <use href="#SvgjsPath1219" x="270" y="570" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="330" y="30" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="330" y="90" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="330" y="150" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="330" y="210" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="330" y="270" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="330" y="330" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1222" x="330" y="390" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="330" y="450" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="330" y="510" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1220" x="330" y="570" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="390" y="30" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1220" x="390" y="90" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1224" x="390" y="150" stroke="rgba(255, 222, 90, 1)" strokeWidth="3"></use>
              <use href="#SvgjsPath1219" x="390" y="210" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="390" y="270" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="390" y="330" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="390" y="390" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="390" y="450" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="390" y="510" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="390" y="570" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="450" y="30" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="450" y="90" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="450" y="150" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="450" y="210" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="450" y="270" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="450" y="330" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="450" y="390" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="450" y="450" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="450" y="510" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="450" y="570" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="510" y="30" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="510" y="90" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="510" y="150" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="510" y="210" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="510" y="270" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1222" x="510" y="330" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1222" x="510" y="390" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="510" y="450" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1220" x="510" y="510" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="510" y="570" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="570" y="30" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="570" y="90" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="570" y="150" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="570" y="210" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="570" y="270" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="570" y="330" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="570" y="390" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="570" y="450" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="570" y="510" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="570" y="570" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="630" y="30" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="630" y="90" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="630" y="150" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="630" y="210" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="630" y="270" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="630" y="330" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="630" y="390" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="630" y="450" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="630" y="510" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1222" x="630" y="570" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="690" y="30" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="690" y="90" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1220" x="690" y="150" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="690" y="210" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="690" y="270" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1220" x="690" y="330" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1221" x="690" y="390" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1223" x="690" y="450" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="690" y="510" stroke="rgba(255, 222, 90, 1)"></use>
              <use href="#SvgjsPath1219" x="690" y="570" stroke="rgba(255, 222, 90, 1)"></use>
            </symbol>
          </svg>
          <div className=" absolute flex gap-4 w-4/5 h-4/5 top-1/2 left-1/2 -translate-x-1/2 z-10 -translate-y-1/2">
            <div className="flex w-full">
              <img src={cms?.whoWeAre?.image} alt="" className=" w-full h-full object-cover relative opacity-10" />
            </div>
            <div className="flex w-full">
              <img src={cms?.whatWeDo?.image} alt="" className=" w-full h-full object-cover relative opacity-10" />
            </div>
            <div className="flex w-full">
              <img src={cms?.whoWeAre?.image} alt="" className=" w-full h-full object-cover relative opacity-10" />
            </div>
          </div>
          <div className="order-2 z-20 lg:order-1 flex justify-center items-center flex-col gap-4">
            {/* <p className="text-primary font-bold text-lg mb-3">STUDY WITH US</p> */}
            <h1 className="text-4xl md:text-6xl font-extrabold text-white capitalize mb-3">{cms?.hero?.header || "Think Solution"}</h1>
            <p className="md:text-lg text-gray-400 w-3/5">{cms?.hero?.text || "We provide solutions and services in the Power, Oil and Gas, Security, Agribusiness, Infrastructral Development and Real Estate Sectors."}</p>
            <Button onClick={() => router.push(`/products`)} className={`py-2 pb-2.5 px-6 text-lg text-blue font-semibold bg-gold rounded-full`}>
              Learn More
            </Button>
          </div>
        </section>
        <section className="section flex flex-col overflow-hidden gap-3 relative pt-16 md:pt-28">
          <svg className="absolute top-0 left-0 min-w-full rotate-180 opacity-20" xmlns="http://www.w3.org/2000/svg" version="1.1" width="1440" height="250" preserveAspectRatio="none" viewBox="0 0 1440 250"><g mask="url(&quot;#SvgjsMask1063&quot;)" fill="none"><path d="M20 250L270 0L567 0L317 250z" fill="url(&quot;#SvgjsLinearGradient1064&quot;)"></path><path d="M258.6 250L508.6 0L759.1 0L509.1 250z" fill="url(&quot;#SvgjsLinearGradient1064&quot;)"></path><path d="M518.2 250L768.2 0L1120.7 0L870.7 250z" fill="url(&quot;#SvgjsLinearGradient1064&quot;)"></path><path d="M754.8000000000001 250L1004.8000000000001 0L1330.3000000000002 0L1080.3000000000002 250z" fill="url(&quot;#SvgjsLinearGradient1064&quot;)"></path><path d="M1421 250L1171 0L941.5 0L1191.5 250z" fill="url(&quot;#SvgjsLinearGradient1065&quot;)"></path><path d="M1190.4 250L940.4000000000001 0L896.9000000000001 0L1146.9 250z" fill="url(&quot;#SvgjsLinearGradient1065&quot;)"></path><path d="M942.8 250L692.8 0L497.79999999999995 0L747.8 250z" fill="url(&quot;#SvgjsLinearGradient1065&quot;)"></path><path d="M697.1999999999999 250L447.19999999999993 0L178.69999999999993 0L428.69999999999993 250z" fill="url(&quot;#SvgjsLinearGradient1065&quot;)"></path><path d="M1220.697497010788 250L1440 30.697497010788L1440 250z" fill="url(&quot;#SvgjsLinearGradient1064&quot;)"></path><path d="M0 250L219.302502989212 250L 0 30.697497010788z" fill="url(&quot;#SvgjsLinearGradient1065&quot;)"></path></g><defs><mask id="SvgjsMask1063"><rect width="1440" height="250" fill="#ffffff"></rect></mask><linearGradient x1="0%" y1="100%" x2="100%" y2="0%" id="SvgjsLinearGradient1064"><stop stopColor="rgba(9, 15, 59, 1)" offset="0"></stop><stop stopOpacity="0" stopColor="rgba(9, 15, 59, 1)" offset="0.66"></stop></linearGradient><linearGradient x1="100%" y1="100%" x2="0%" y2="0%" id="SvgjsLinearGradient1065"><stop stopColor="rgba(9, 15, 59, 1)" offset="0"></stop><stop stopOpacity="0" stopColor="rgba(9, 15, 59, 1)" offset="0.66"></stop></linearGradient></defs></svg>
          <h2 className="text-blue font-extrabold text-3xl md:text-5xl  mb-4 md:mb-12 text-center">About Us</h2>
          <div className="flex flex-col gap-6 md:gap-12">
            <div className="flex flex-col h-fit lg:flex-row justify-center items-center gap-4 md:gap-12">
              <div className="flex flex-1 scale-75 flex-col gap-4 overflow-hidden ">
              <img src={cms?.whoWeAre?.image} alt="image" className="w-full h-full object-cover" />
              </div>
              <div className="flex flex-1 justify-center items-center lg:items-start flex-col w-fit gap-4">
                <h2 className="text-2xl md:text-3xl font-extrabold w-fit text-blue mb-3">Who We Are</h2>
                <p className="md:text-lg text-center lg:text-left mb-4 lg:w-2/3">{cms?.whoWeAre?.text || "Eraskon Nigeria Limited (ENL) is an indigenous Security and Logistics services provider in the Oil & Gas and Marine sectors of the Nigerian economy with the vision of delivering top rated security services as required by clients while optimizing client’s profit and minimizing operational cost."}</p>
              </div>
            </div>
            <div className="flex flex-col lg:flex-row justify-center items-center gap-4 md:gap-12">
              <div className="flex lg:order-2 flex-1 scale-75 flex-col gap-4 overflow-hidden ">
                <img src={cms?.whatWeDo?.image} alt="image" className="w-full h-full object-cover" />
              </div>
              <div className="flex flex-1 justify-center items-end lg:items-end flex-col w-fit gap-4">
                <h2 className="text-2xl md:text-3xl text-center w-full lg:text-right font-extrabold text-blue capitalize mb-3">What We Do</h2>
                <p className="md:text-lg text-center lg:w-2/3 lg:text-right mb-4">{cms?.whatWeDo?.text || "Eraskon Nigeria Limited (ENL) Offers a wide range of services to manage all forms of security threats, such as early warning systems/inteligence gathering, vulerability accessments, wtc. Eraskon Nigeria Limited (ENL) is duly licensed by the Department of Petroleum Resources (DPR) and the Nigeria Security & Civil Defence COrp (NSCDC) to provide security services. ENL is a corporate member of the Nigerian Institute for Industrial Security (NIIS)"}</p>
              </div>
            </div>
            {/* <div className="grid lg:grid-cols-2 gap-4 md:gap-12">
              <div className="flex-1 w-full lg:order-1 flex flex-col gap-4">
                <Image src={MyImage} alt="image"/>
              </div>
              <div className="flex-1 order-2 lg:order-1 flex flex-col gap-4">
                <h2 className="text-2xl md:text-3xl font-extrabold text-blue capitalize mb-3">What We Do</h2>
                <p className="md:text-lg mb-4">{cms?.whatWeDo?.text || "Eraskon Nigeria Limited (ENL) Offers a wide range of services to manage all forms of security threats, such as early warning systems/inteligence gathering, vulerability accessments, wtc. Eraskon Nigeria Limited (ENL) is duly licensed by the Department of Petroleum Resources (DPR) and the Nigeria Security & Civil Defence COrp (NSCDC) to provide security services. ENL is a corporate member of the Nigerian Institute for Industrial Security (NIIS)"}</p>
              </div>
            </div> */}
          </div>
        </section>

        <section className="section py-12 md:py-20 text-center">
          <div className="flex flex-col items-center gap-4 max-w-2xl mx-auto mb-12">
            {/* <h2 className="text-primary font-bold text-2xl">Our Programmes</h2> */}
            <h3 className="text-3xl md:text-5xl font-extrabold capitalize mb-3">
              Our Products
            </h3>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {
              products?.length > 0 ? (
                products?.map((item: IProduct, index: number) => (
                  <Product key={index} product={item} handleClick={handleClick} mode="user" />
                ))
              ) : (
                <div className="flex flex-col items-center justify-center gap-4">
                  <h1 className="text-2xl font-argentinum">No Products</h1>
                </div>
              )
            }
          </div>
        </section>

        {/* <Advisory advisory={advisory} /> */}
        <Footer />
      </div>
    </div>
  );
}


export const getServerSideProps = async () => {
  let cms = {}
  let products = []
  try {
    await dbConnect()
    const res = await CmsModel.findOne({}).lean();
    cms = JSON.parse(JSON.stringify(res))

    const response = await ProductModel.find({}).lean();
    products = JSON.parse(JSON.stringify(response))

    // console.log({news_res})
    // news = JSON.parse(JSON.stringify(news_res))

  } catch (error) {
    console.log(error)
    return {
      props: {
        cms: {},
        products: [],
        status: 'failed'
      }
    }
  }


  return {
    props: {
      cms,
      products,
      status: 'success'
    }
  }
}