import Head from "next/head";
import { FormEvent, useEffect, useReducer, useState } from 'react'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Button from "@/components/Button";
import Image from "next/image";
import HeroImg from '@/assets/img1.png'
import QualifiedImg from '@/assets/img2.png'
import HeroBg from '@/assets/hero-bg.png'
import PrimaryImg from '@/assets/primary.png'
import Primary1Img from '@/assets/primary-1.png'
import SecondaryImg from '@/assets/school.png'
import UniversityImg from '@/assets/university.png'
import PostGradImg from '@/assets/postgraduate.png'
import TeacherImg from '@/assets/teacher.png'
import StudentImg from '@/assets/student.png'
import AmazedImg from '@/assets/amazed.png'
import NewsImg from '@/assets/news.png'
import GradImg from '@/assets/graduation.png'
import { BiCircle } from 'react-icons/bi'
import Link from "next/link";
import { ICms, INews, IReducerAction } from '@/interfaces'
import usePost from '@/hooks/usePost';
import { toast } from 'react-toastify';
import Loader from '@/components/Loader';
import Ambassadors from "@/components/Ambassadors";
import { IProduct } from "@/interfaces";
import Product from "@/components/ProductCard";
import dbConnect from '@/lib/dbConnection';
import CmsModel from '@/models/CmsModel';
import ProductModel from '@/models/ProductModel';
import { useRouter } from "next/router";
import NewsCard from "@/components/NewsCard";
import { AiOutlineCheck } from "react-icons/ai";
import { chmodSync } from "fs";


export default function Home({ cms, products }: { cms: ICms, products: IProduct[] }) {
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>Brilliant Brains</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconimg.png" />
      </Head>
      <div className="">
        {/* {loading && <Loader modalOpen={true} />} */}
        <Header />
        <section className="section top-section pb-12 overflow-hidden lg:min-h-screen lg:mt-0 lg:pt-40">
          <div className="grid lg:grid-cols-2 gap-8 md:gap-12">
            <div className="order-2 lg:order-1 flex flex-col gap-4">
              {/* <p className="text-primary font-bold text-lg mb-3">STUDY WITH US</p> */}
              <h1 className="text-4xl md:text-6xl font-extrabold capitalize mb-3">{cms?.hero?.header || "Think Solution"}</h1>
              <p className="md:text-lg">{cms?.hero?.text || "We provide solutions and services in the Power, Oil and Gas, Security, Agribusiness, Infrastructral Development and Real Estate Sectors."}</p>
              <a href ="https://box.reinsys.net/brilliant/" className="flex justify-between items-center bg-gray-100 rounded-xl max-w-md text-sm md:text-base">
                <p className="ml-4">Lets get started</p>
                {/* <a href={`https://box.reinsys.net/brilliant/`} className="grad-to-right text-white text-sm md:text-base px-6 py-3 rounded-xl w-fit">Connect with us</a> */}
                <Button className="rounded-xl text-white py-3 md:py-4 px-5">Connect with us</Button>
              </a>
            </div>
          </div>
        </section>
        <section className="section">
          <div className="grid lg:grid-cols-2 gap-4 md:gap-12">
            <div className="flex-1 order-2 lg:order-1 flex flex-col gap-4">
              <h2 className="text-2xl md:text-3xl font-extrabold text-blue capitalize mb-3">Who We Are</h2>
              <p className="md:text-lg mb-4">{cms?.whoWeAre?.text || "Eraskorp Nigeria Limited (ENL) is an indigenous Security and Logistics services provider in the Oil & Gas and Marine sectors of the Nigerian economy with the vision of delivering top rated security services as required by clients while optimizing client’s profit and minimizing operational cost."}</p>
            </div>
            <div className="w-full h-full min-h-96 order-1 lg:order-2 flex flex-col  justify-end relative">
              
            </div>
          </div>
          <div className="grid lg:grid-cols-2 gap-4 md:gap-12">
            <div className="flex-1 order-2 lg:order-1 flex flex-col gap-4">
              <h2 className="text-2xl md:text-3xl font-extrabold text-blue capitalize mb-3">What We Do</h2>
              <p className="md:text-lg mb-4">{cms?.whatWeDo?.text || "Eraskorp Nigeria Limited (ENL) Offers a wide range of services to manage all forms of security threats, such as early warning systems/inteligence gathering, vulerability accessments, wtc. Eraskorp Nigeria Limited (ENL) is duly licensed by the Department of Petroleum Resources (DPR) and the Nigeria Security & Civil Defence COrp (NSCDC) to provide security services. ENL is a corporate member of the Nigerian Institute for Industrial Security (NIIS)"}</p>
            </div>
            <div className="w-full h-full min-h-96 order-1 lg:order-2 flex flex-col  justify-end relative">
              
            </div>
          </div>
        </section>

        <section className="section py-12 md:py-20 text-center">
          <div className="flex flex-col items-center gap-4 max-w-2xl mx-auto mb-12">
            {/* <h2 className="text-primary font-bold text-2xl">Our Programmes</h2> */}
            <h3 className="text-3xl md:text-5xl font-extrabold capitalize mb-3">
              Our Products
            </h3>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {
            products?.length > 0 ? (
              products?.map((item: IProduct, index: number) => (
                <Product key={index} product={item} mode="user"/>
              ))
            ) : (
              <div className="flex flex-col items-center justify-center gap-4">
                <h1 className="text-2xl font-argentinum">No Products</h1>
              </div>  
            )
          }
        </div>
        </section>
               
        {/* <Advisory advisory={advisory} /> */}
        <Footer />
      </div>
    </div>
  );
}


export const getServerSideProps = async () => {
  let cms = {}
  let products = []
  try {
      await dbConnect()
      const res = await CmsModel.findOne({}).lean();
      cms = JSON.parse(JSON.stringify(res))

      const response = await ProductModel.find({}).lean();
      products = JSON.parse(JSON.stringify(response))

      // console.log({news_res})
      // news = JSON.parse(JSON.stringify(news_res))
      
  } catch (error) {
      console.log(error)
      return {
          props: {
              cms: {},
              products: [],
              status: 'failed'
          }
      }
  }


  return {
      props: {
          cms,
          products,
          status: 'success'
      }
  }
}